import { createApp } from 'vue';
import { Slider, Row, Col, Select } from 'ant-design-vue';
import Derectives from '@/derective/index';
import App from './App.vue';
import STUI from './packages/index';
import './styles/index.less';
import 'element-plus/dist/index.css';
const app = createApp(App);
Slider.install(app);
Row.install(app);
Col.install(app);
Select.install(app);
app.use(STUI);
app.use(Derectives);
app.mount('#app');
